baseURL = 'https://rosaainz.github.io/RosaSainz-Blog/'
languageCode = 'en-us'
title = 'TechBagaje'
theme = 'risotto'

[params.theme]
palette = "base16-dark"

# Sidebar: about/bio
[params.about]
title = "TechBagaje"
description = "ğŸ› My learning journal"

[menu]

  [[menu.main]]
    identifier = "about"
    name = "About"
    url = "/about/"
    weight = 10

[[menu.main]]
    identifier = "posts"
    name = "Prueba"
    url = "/posts/"
    weight = 10
